<a href="https://colab.research.google.com/github/amzangi/datascience-bootcamp/blob/master/2_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
L = list(range(11))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
type(L[0])

int

In [ ]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10']

In [ ]:
type(L2[0])

str

In [ ]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Remember that unlike Python lists, NumPy is constrained to arrays that all contain the same type. 
np.array([3.14, 1, 3])

array([3.14, 1.  , 3.  ])

In [ ]:
# To explicitly set the data type
np.array([1,2,3,4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [ ]:
# Unlike Python lists, NumPy arrays can explicitly be multidimensional.
np.array([range(i, i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

## Using routines built into NumPy

In [ ]:
# array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# array filled with ones
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# array filled with 3.14
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [ ]:
# array filled with a linear sequence. Starting at 0, ending at 20, stepping by 2
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
# array of five values evenly spaced between 1 and 10
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
# array of uniformly distributed random values between 0 and 1
np.random.random((3,3))

array([[0.14453594, 0.9806762 , 0.88065445],
       [0.40727705, 0.23546326, 0.41532005],
       [0.78353334, 0.8846138 , 0.55713133]])

In [ ]:
# array of uniformly distributed random values between mean 0 and standard deviation 1
np.random.normal(0,1,(3,3))

array([[-1.18512073,  0.33955271, -0.89650729],
       [ 0.7147257 , -1.66217417, -0.26086993],
       [-1.44824334,  1.4306985 , -0.35748974]])

In [ ]:
# array of random integers in the interval 0 and 10
np.random.randint(0,10,(3,3))

array([[0, 3, 9],
       [0, 7, 6],
       [7, 2, 4]])

In [ ]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.zeros(10, dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [ ]:
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [ ]:
# seed for reproductivity
np.random.seed(0)

In [ ]:
# 1 Dimensional
x1 = np.random.randint(10, size=6)
# 2 Dimensional
x2 = np.random.randint(10, size=(3,4))
# 3 Dimensional
x3 = np.random.randint(10, size=(3,4,5))

In [ ]:
# 2 - Dimensional
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [ ]:
x2.ndim, x2.shape, x2.size, x2.dtype

(2, (3, 4), 12, dtype('int64'))

In [ ]:
# 3 - Dimensional
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [ ]:
x3.ndim, x3.shape, x3.size, x3.dtype

(3, (3, 4, 5), 60, dtype('int64'))

## Array Indexing

In [ ]:
x1

array([5, 0, 3, 3, 7, 9])

In [ ]:
x1[0],x1[-1]

(5, 9)

In [ ]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [ ]:
# In a multidimensional array, you access items using a comma-separated tuple of indices
x2[0,0], x2[1,2], x2[2,-2]

(3, 8, 7)

In [ ]:
# unlike Python lists, NumPy arrays have a fixed type. 
# This means, for example, that if you attempt to insert a floating-point value to an integer array, 
# the value will be silently truncated.
x2[0,0]=3.11
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

## Array Slicing:  x[start:stop:step]
#### If any of these are unspecified, they default to the values start=0, stop=size of dimension, step=1.

In [ ]:
x4 = np.arange(10)
x4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x4[:3], x4[3:], x4[:3:]

(array([0, 1, 2]), array([3, 4, 5, 6, 7, 8, 9]), array([0, 1, 2]))

In [ ]:
x4[2:5], x4[:5:2], x4[0::2] 

(array([2, 3, 4]), array([0, 2, 4]), array([0, 2, 4, 6, 8]))

In [ ]:
# Start and stopped are swapped with negative step value
x4[:5:-1], x4[5::-1]

(array([9, 8, 7, 6]), array([5, 4, 3, 2, 1, 0]))

In [ ]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [ ]:
# For indexing Two Dimenional Arrays, we need 2 indexes separated by comma. First for ROWS, second for COLUMNS. 
# two rows, three columns
x2[:2,:3]

array([[3, 5, 2],
       [7, 6, 8]])

In [ ]:
# all rows, every other column
x2[:3,::2]

array([[3, 2],
       [7, 8],
       [1, 7]])

In [ ]:
# subarray dimensions can even be reversed together:
x2[::-1,::-1]

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

In [ ]:
# First Column
x2[:,0]

array([3, 7, 1])

In [ ]:
# First Row. Comma & Colon can be omitted.
x2[0,:], x2[0]

(array([3, 5, 2, 4]), array([3, 5, 2, 4]))

In [ ]:
# Numpy array slices are views rather than copies of original data. Change in a slice is inherited by the array. e.g.:
x2[:2,:2]

array([[3, 5],
       [7, 6]])

In [ ]:
x2b = x2[:2,:2]
x2b[0,0] = 99
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [ ]:
x2b_copy = x2b.copy()
x2b_copy[0,0] = 999
x2b_copy

array([[999,   5],
       [  7,   6]])

In [ ]:
x2b

NameError: ignored

## Reshaping of Arrays

In [ ]:
x5 = np.arange(1,10)
x5

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# size of the initial array must match the size of the reshaped array.
grid1 = x5.reshape((3,3))
grid1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
x6 = np.array([1,2,3])
# column vector via reshape
x6.reshape((3,1))

array([[1],
       [2],
       [3]])

In [ ]:
# column vector via newaxis
x6[:,np.newaxis]

array([[1],
       [2],
       [3]])

## Array Concatenation and Splitting

In [ ]:
x7 = np.array([1,2,3])
x8 = np.array([4,5,6])
x9 = [99,100,101]
np.concatenate([x7,x8,x9])

array([  1,   2,   3,   4,   5,   6,  99, 100, 101])

In [ ]:
grid2 = np.array([[1,2,3],[4,5,6]])

In [ ]:
# concatenate along the first axis
np.concatenate([grid2,grid2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid2,grid2], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [ ]:
# vertically stack the arrays of mixed dimension
np.vstack([x9,grid2])

array([[ 99, 100, 101],
       [  1,   2,   3],
       [  4,   5,   6]])

In [ ]:
# horizontally stack the arrays of mixed dimension
x10 = np.array([[22],[44]])
np.hstack([x10,grid2])

array([[22,  1,  2,  3],
       [44,  4,  5,  6]])

In [ ]:
x11 = [1,2,3,44,55,6,7,8]
x12, x13, x14 = np.split(x11, [3,4])
print (x12, x13, x14)

[1 2 3] [44] [55  6  7  8]


In [ ]:
grid3 = np.arange(0,16).reshape(4,4) 
grid3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.vsplit(grid3, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [ ]:
np.hsplit(grid3, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

## Universal Functions

In [ ]:
x10 = np.arange(4)
x10 , x10 + 2 , x10 * 2, x10 / 2 , x10 // 2 , -x10 , x10**2 , x10 % 2

(array([0, 1, 2, 3]),
 array([2, 3, 4, 5]),
 array([0, 2, 4, 6]),
 array([0. , 0.5, 1. , 1.5]),
 array([0, 0, 1, 1]),
 array([ 0, -1, -2, -3]),
 array([0, 1, 4, 9]),
 array([0, 1, 0, 1]))

In [ ]:
x11 = -(2 * x10 + 1) **2
x11 , abs(x11)

(array([ -1,  -9, -25, -49]), array([ 1,  9, 25, 49]))

In [ ]:
x12 = np.linspace(0, np.pi, 3)
x12 , np.sin(x12) , np.cos(x12) , np.tan(x12)

(array([0.        , 1.57079633, 3.14159265]),
 array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16]),
 array([ 1.000000e+00,  6.123234e-17, -1.000000e+00]),
 array([ 0.00000000e+00,  1.63312394e+16, -1.22464680e-16]))

In [ ]:
x13 = [1, 0 , -1]
x13, np.arcsin(x13) , np.arccos(x13) , np.arctan(x13)

([1, 0, -1],
 array([ 1.57079633,  0.        , -1.57079633]),
 array([0.        , 1.57079633, 3.14159265]),
 array([ 0.78539816,  0.        , -0.78539816]))

In [ ]:
x14 = [1, 2, 3]
np.exp(x14), np.exp2(x14), np.power(2, x14)

(array([ 2.71828183,  7.3890561 , 20.08553692]),
 array([2., 4., 8.]),
 array([2, 4, 8]))

In [ ]:
x15 = [1, 2, 4, 10]
np.log(x15), np.log2(x15), np.log10(x15)

(array([0.        , 0.69314718, 1.38629436, 2.30258509]),
 array([0.        , 1.        , 2.        , 3.32192809]),
 array([0.        , 0.30103   , 0.60205999, 1.        ]))

In [ ]:
# calling reduce on ufunc returns the sum and multiplication of all elements in the array
np.add.reduce(x15), np.multiply.reduce(x15) 

(17, 80)

In [ ]:
# calling acumulate on ufunc returns the intermediate results of computation
np.add.accumulate(x15), np.multiply.accumulate(x15)

(array([ 1,  3,  7, 17]), array([ 1,  2,  8, 80]))

In [ ]:
# multiplicaton table
np.add.outer(x15, x15)

array([[ 2,  3,  5, 11],
       [ 3,  4,  6, 12],
       [ 5,  6,  8, 14],
       [11, 12, 14, 20]])

In [ ]:
# 1-D array is straightforward , let see 2-d array
x16 = np.random.random((2,3))
x16

array([[0.65279032, 0.63505887, 0.99529957],
       [0.58185033, 0.41436859, 0.4746975 ]])

In [ ]:
np.sum(x16), np.min(x16), np.max(x16)

(3.7540651782402583, 0.4143685882263688, 0.9952995676778876)

In [ ]:
# min value along each column
np.min(x16, axis=0)

array([0.58185033, 0.41436859, 0.4746975 ])

In [ ]:
# min value along each row
np.min(x16, axis=1)

array([0.63505887, 0.41436859])

In [ ]:
# Some important functios
np.mean, np.std, np.percentile, np.median

(<function numpy.mean>,
 <function numpy.std>,
 <function numpy.percentile>,
 <function numpy.median>)

## Broadcasting

In [ ]:
#Recall that for arrays of the same size, binary operations are performed on an element-by-element basis.
#Broadcasting allows these types of binary operations to be performed on arrays of different sizes

x17 = np.array([3,3,3,3,3])
x17 + 1

array([4, 4, 4, 4, 4])

In [ ]:
x18 = np.ones((3,3))
x18 + 1
#Here 1-D array is stretched, or broadcast, across the second dimension in order to match the shape of x18.

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [ ]:
x19 = np.arange(3)
x20 = np.arange(3)[:,np.newaxis]
x19, x20

(array([0, 1, 2]), array([[0],
        [1],
        [2]]))

In [ ]:
x18.shape, x19.shape, x20.shape

((3, 3), (3,), (3, 1))

In [ ]:
x19 + x20

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [ ]:
x18 + x19

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [ ]:
x18 + x20

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [ ]:
x21 = np.ones((2,3))
x21 , x21.shape

(array([[1., 1., 1.],
        [1., 1., 1.]]), (2, 3))

In [ ]:
# (2,3) & (3,3) -- Error
x21 + x18

ValueError: ignored

In [ ]:
# (2,3) & (3,) 
x21 + x19

array([[1., 2., 3.],
       [1., 2., 3.]])

In [ ]:
# (2,3) & (3,1) -- Error
x21 + x20

ValueError: ignored

#### <font color = 'Red'>Centering an array

#### <font color = 'Red'> Plotting a two-dimensional function

## Comparisons, Masks, and Boolean Logic

In [ ]:
x21 = np.array([1,2,3,4,5,6,7,8,9])

In [ ]:
x21 > 3

array([False, False, False,  True,  True,  True,  True,  True,  True])

In [ ]:
x21 <= 3

array([ True,  True,  True, False, False, False, False, False, False])

In [ ]:
x21 == 3

array([False, False,  True, False, False, False, False, False, False])

In [ ]:
# element-by-element comparison of two arrays, and to include compound expressions.
(2 * x21) == (x21 **2)

array([False,  True, False, False, False, False, False, False, False])

In [ ]:
# 2-D array
rng = np.random.RandomState(0)
x22 = rng.randint(10, size=(3,4))
x22

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [ ]:
x22 < 6

array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False, False]])

In [ ]:
# How many values less than 6
np.count_nonzero(x22 < 6)

8

In [ ]:
# In this case, False is interpreted as 0, and True is interpreted as 1.
np.sum(x22 < 6)

8

In [ ]:
# This counts the number of values less than 6 in each row of the matrix.
np.sum(x22 < 6, axis = 1)

array([4, 2, 2])

In [ ]:
# are there any values greater than 8?
np.any(x22 > 8)

True

In [ ]:
# are all values less than 7?
np.all(x22 > 7)

False

In [ ]:
# are all values in each row less than 4?
np.all(x22 < 4, axis = 1)

array([False, False, False])

In [ ]:
# any values in each row less than 4?
np.any(x22 < 4, axis = 1)

array([ True,  True,  True])

In [ ]:
# compound questions
np.sum((x22 > 3) & (x22 <6))

3

In [ ]:
# Maskig which produces 1-D array
x23 = x22[x22 < 6]
x23

array([5, 0, 3, 3, 3, 5, 2, 4])

In [ ]:
# Running operations on the masked array
np.sum(x23), np.min(x23), np.median(x23) 

(25, 0, 3.0)

In [ ]:
# Using AND OR vs. & |
x24 = np.array([1, 0, 1, 0, 1, 0], dtype = bool)
x25 = np.array([1, 1, 1, 0, 1, 1], dtype = bool)
x24 | x25

array([ True,  True,  True, False,  True,  True])

In [ ]:
# Using or on these arrays will try to evaluate the truth or falsehood of the entire array object, 
# which is not a well-defined value.
x24 OR x25 -- Error

SyntaxError: ignored

## Fancy Indexing

In [ ]:
x26 = np.array([51,92,14,71,60,20,82,86,74,74])

In [ ]:
[x26[3],x26[4], x26[7]] 

[71, 60, 86]

In [ ]:
ind = [3, 4, 7]
x26[ind]

array([71, 60, 86])

In [ ]:
# With fancy indexing, the shape of the result reflects the shape of the index arrays,
# rather than the shape of the array being indexed.
ind2 = np.array([[2,4],[5,7]])
x26[ind2]

array([[14, 60],
       [20, 86]])

In [ ]:
# Fancy indexing also works in multiple dimensions.
x27 = np.arange(12).reshape((3,4))
x27

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
row = np.array([0,1,2])
col = np.array([3,2,1])
x27[row,col]
# Notice that the first value in the result is X[0, 3], the second is X[1, 2], and the third is X[2, 1].

array([3, 6, 9])

In [ ]:
row2 = row[:, np.newaxis]
row2

array([[0],
       [1],
       [2]])

In [ ]:
x27[row2,col]

array([[ 3,  2,  1],
       [ 7,  6,  5],
       [11, 10,  9]])

In [ ]:
# Similarly performing arithmetic operations
row2 * col

array([[0, 0, 0],
       [3, 2, 1],
       [6, 4, 2]])

In [ ]:
# Combined Indexing. 
x27

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# [2] is for row, while [2,0,1] for cols.
x27[2,[2,0,1]]

array([10,  8,  9])

In [ ]:
x27[1:,[2,0,1]]

array([[ 6,  4,  5],
       [10,  8,  9]])

In [ ]:
x27, row2, np.array([1,0,1,0], dtype=bool)

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]), array([[0],
        [1],
        [2]]), array([ True, False,  True, False]))

In [ ]:
mask =np.array([1,0,1,0], dtype=bool)

In [ ]:
x27[row2,mask]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

#### <font color = 'Red'>Selecting Random Points

In [ ]:
# Modifying Values with Fancy Indexing
x28 = np.arange(10)
x29 = np.array([2,1,8,4])
print(x28)
print(x29)

[0 1 2 3 4 5 6 7 8 9]
[2 1 8 4]


In [ ]:
x28[x29]=99
print(x28)

[ 0 99 99  3 99  5  6  7 99  9]


In [ ]:
# subtracting 10 
x28[x29] -= 10
# it is a short hand for x28[x29] = x28[x29] - 10
print(x28)

[ 0 89 89  3 89  5  6  7 89  9]


In [ ]:
x30 = np.zeros(10)
print(x30)
x30[[0,1]] = [4,6]
print(x30)
x30[[0,0]] = [77,88]
# First assigned 77 and then 88
print(x30)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[4. 6. 0. 0. 0. 0. 0. 0. 0. 0.]
[88.  6.  0.  0.  0.  0.  0.  0.  0.  0.]


#### <font color = 'Red'>Example: Binning Data

### Fast Sorting in NumPy:

In [ ]:
x31 = np.array([2, 1, 4, 3, 5])
print(x31)
# Sorting without modifying the input
print(np.sort(x31))
# Sorting the array in place
x31.sort()
print(x31)

[2 1 4 3 5]
[1 2 3 4 5]
[1 2 3 4 5]


In [ ]:
x32 = np.array([3,1,6,2,7,9])
# returning the indices of the sorted elements  
print(x32)
print(np.argsort(x32))

[3 1 6 2 7 9]
[1 3 0 2 4 5]


In [ ]:
rand2 = np.random.RandomState(42)
x33 = rand2.randint(0, 10, (4, 6))
print(x33)

# Sorting each column
print(np.sort(x33, axis = 0))

# Sorting each row
print(np.sort(x33, axis = 1))

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]
[[2 1 4 0 1 5]
 [5 2 5 4 3 7]
 [6 3 7 4 6 7]
 [7 6 7 4 9 9]]
[[3 4 6 6 7 9]
 [2 3 4 6 7 7]
 [1 2 4 5 7 7]
 [0 1 4 5 5 9]]


In [ ]:
# np.partition takes an array and a number K; the result is a new array.
x34 = np.array([2,4,1,5,7,3,3,39])
np.partition(x34, 3)
# Within the two partitions, the elements have arbitrary order

array([ 2,  1,  3,  3,  4,  5,  7, 39])

In [ ]:
np.partition(x33, 2, axis =1)
# first two slots in each row contain the smallest values from that row

array([[3, 4, 6, 7, 6, 9],
       [2, 3, 4, 7, 6, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 9, 5]])

#### <font color = 'Red'>k-Nearest Neighbors

### NumPy’s Structured Arrays

In [ ]:
name = ['Alice', 'Bob', 'Cathy', 'Doug']
age = [25, 45, 37, 19]
weight = [55.0, 85.5, 68.0, 61.5]
# Nothing tells us that it is related. How can we use single structure to store all this data.

In [ ]:
# Use a compound data type for structured arrays. We will creat an empty container array,
data = np.zeros(4, dtype ={ 'names': ('name', 'age', 'weight'), 'formats':('U10', 'i4', 'f8')})
print(data.dtype)
# 'U10' translates to “Unicode string of maximum length 10,” 
# 'i4' translates to “4-byte (i.e., 32 bit) integer,” 
# 'f8' translates to “8-byte (i.e., 64 bit) float.”

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]


In [ ]:
# We will fill the empty cotainer array with our list of values
data['name'] = name
data['age'] = age
data['weight'] = weight
print(data)

[('Alice', 25, 55. ) ('Bob', 45, 85.5) ('Cathy', 37, 68. )
 ('Doug', 19, 61.5)]


In [ ]:
# Now we can use names or indexes
data['name']

array(['Alice', 'Bob', 'Cathy', 'Doug'], dtype='<U10')

In [ ]:
# First row of data
data[0]

('Alice', 25, 55.)

In [ ]:
# Getting name from last row
data[-1]['name']

'Doug'

In [ ]:
# Getting name with age < 30
data[data['age']<30]['name']

array(['Alice', 'Doug'], dtype='<U10')

In [ ]:
# Pandas provides a DataFrame object, which is a structure built on NumPy arrays. 
# It offers a variety of useful data manipulation functionality similar to what we’ve seen here

In [ ]:
# Field can be accessed as attributes rather than dictionary keys through record arrays. 
# However, there is an overhead using this method when accessing the fields
data_rec = data.view(np.recarray)
data['age'], data_rec.age

(array([25, 45, 37, 19], dtype=int32), array([25, 45, 37, 19], dtype=int32))